---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: mysql
    component: backend

spec:
  containers:
  - name: mysql-db
    image: 280756408574.dkr.ecr.us-east-1.amazonaws.com/db:latest
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: pass123
    - name: MYSQL_DATABASE
      value: employees
    ports:
        - containerPort: 3306
          protocol: TCP
