apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: employees
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      serviceAccountName: project-g2  # Assign the created ServiceAccount
      containers:
        - name: app
          image: 280756408574.dkr.ecr.us-east-1.amazonaws.com/app:latest
          ports:
            - containerPort: 81
          env:
            - name: DBHOST
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: DBHOST
            - name: DBPORT
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: DBPORT
            - name: DBUSER
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: DBUSER      
            
              
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: DATABASE
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-database
            
              
            - name: GROUP_NAME
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: GROUP_NAME
            - name: IMAGE_URL
              valueFrom:
                configMapKeyRef:
                  name: app
                  key: IMAGE_URL
